# Generated by Django 3.2.8 on 2021-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habiliades'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(default=2, upload_to='empleado'),
            preserve_default=False,
        ),
    ]
