# Generated by Django 3.2.8 on 2021-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20211011_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, upload_to='empleado'),
        ),
    ]
