# Generated by Django 3.2.8 on 2021-10-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20211014_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre Completo'),
        ),
    ]
