# Generated by Django 3.2.8 on 2021-10-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_shor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='active',
            new_name='anulate',
        ),
    ]
